on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
  
    - run: |
           cd front-end
           npm install
           npm i @angular/cli@12.1.4 -g
           ng build

    - run: |
           npm install       
           npm install -g vsce
           npm run test
           vsce package
